In [ ]:
import torch

In [ ]:
liste = [[1,2,3],[4,5,6]]
tensor = torch.tensor(liste)

In [ ]:
import numpy as np
np_array = np.array(liste)
np_tensor = torch.from_numpy(np_array)

In [ ]:
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor.device

device(type='cpu')

## Operasyonlar

In [ ]:
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[2,2],[3,3]])

In [ ]:
a+b

tensor([[3, 3],
        [5, 5]])

In [ ]:
a*b

tensor([[2, 2],
        [6, 6]])

## İlk Sinir Ağı

In [ ]:
import torch.nn as nn
input_tensor = torch.tensor(
    [[0.3471,0.4547,-0.2356]]
    )

In [ ]:
input_tensor.shape

torch.Size([1, 3])

In [ ]:
dogrusal_layer = nn.Linear(in_features=3,out_features=2)

In [ ]:
cikti = dogrusal_layer(input_tensor)
print(cikti)

tensor([[0.1735, 0.3622]], grad_fn=<AddmmBackward0>)


In [ ]:
dogrusal_layer.weight

Parameter containing:
tensor([[ 0.0296,  0.5369,  0.1465],
        [-0.0910, -0.0468,  0.1315]], requires_grad=True)

In [ ]:
dogrusal_layer.bias

Parameter containing:
tensor([-0.0464,  0.4460], requires_grad=True)

## Sequential

In [ ]:
model = nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
    )

`[[2,3,6,7,9,3,2,1]]` <br>
yukarıda yer alan diziden faydalanarak
1. Tensora dönüştürme
2. sıralı (Sequential bir yapı içerisinde 8,4 ve 4,1 lik iki doğrusal katman ekleme
3. modelin çalıştırılması
4. çıktıların ekrana yazılması

In [ ]:
input_tensor = torch.Tensor([[2,3,6,7,9,3,2,1]])
model = nn.Sequential(nn.Linear(8,4),
                      nn.Linear(4,1))

In [ ]:
cikti = model(input_tensor)
print(cikti)

tensor([[0.3526]], grad_fn=<AddmmBackward0>)


In [ ]:
model[0].weight

Parameter containing:
tensor([[ 0.0053, -0.2539, -0.0652,  0.1969, -0.2171,  0.2747,  0.0302,  0.3382],
        [-0.2245,  0.0645,  0.1428,  0.3482, -0.1018,  0.0636, -0.2024,  0.0309],
        [ 0.1176,  0.2483, -0.0566,  0.1176, -0.3031,  0.0618, -0.1514,  0.2294],
        [-0.3348, -0.0890, -0.3043, -0.0442,  0.1370, -0.0145,  0.1318, -0.2340]],
       requires_grad=True)

## Aktivasyon Fonkisyonları
* Sigmoid

In [ ]:
giris = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
sigmoid(giris)

tensor([[0.9975]])

In [ ]:
input_tensor = torch.Tensor([[2,3,6,7,9,3,2,1]])
model = nn.Sequential(nn.Linear(8,4),
                      nn.Linear(4,1),
                      nn.Sigmoid())
model(input_tensor)

tensor([[0.7887]], grad_fn=<SigmoidBackward0>)

* Softmax

In [ ]:
giris = torch.tensor([[4.2,6.1,2.3]])
sigmoid = nn.Sigmoid()
sigmoid(giris)

tensor([[0.9852, 0.9978, 0.9089]])

In [ ]:
giris = torch.tensor([[4.2,6.1,2.3]])
softmax = nn.Softmax(dim=-1)
softmax(giris)

tensor([[0.1276, 0.8533, 0.0191]])

##  forward prop

In [ ]:
giris_veri = torch.tensor(
    [[0.4680, 0.1450, 0.1029, 0.3760, 0.5813, 0.4607, 0.8840, 0.9123, 0.6441,
         0.5628],
        [0.7681, 0.2212, 0.9511, 0.4000, 0.2130, 0.7685, 0.8511, 0.2762, 0.5940,
         0.8605],
    [0.4178, 0.9666, 0.2885, 0.1685, 0.2009, 0.7904, 0.1492, 0.2379, 0.9642,
        0.9226]]
)

In [ ]:
giris_veri.shape

torch.Size([3, 10])

In [ ]:
model = nn.Sequential(
    nn.Linear(10,5),
    nn.Linear(5,1),
    nn.Sigmoid()
)
cikti = model(giris_veri)
print(cikti)

tensor([[0.5340],
        [0.5502],
        [0.4836]], grad_fn=<SigmoidBackward0>)


In [ ]:
for item in cikti:
  if item[0] > 0.5:
    print(1)

1
1


In [ ]:
model = nn.Sequential(
    nn.Linear(10,5),
    nn.Linear(5,3),
    nn.Softmax(dim=-1)
)
cikti = model(giris_veri)
print(cikti)

tensor([[0.3189, 0.3750, 0.3061],
        [0.3358, 0.2971, 0.3671],
        [0.3742, 0.3310, 0.2948]], grad_fn=<SoftmaxBackward0>)


In [ ]:
nn.functional.one_hot(torch.tensor(1),num_classes=3)

tensor([0, 1, 0])

In [ ]:
criterion = nn.CrossEntropyLoss()
skorlar =torch.tensor([[0.2436, 0.3709]])
one_hot_y = torch.tensor([[1,0]])
criterion(skorlar.double(),one_hot_y.double())


tensor(0.7588, dtype=torch.float64)

In [ ]:
model = nn.Sequential(
    nn.Linear(10,5),
    nn.Linear(5,1)
)
cikti = model(giris_veri)
print(cikti)

tensor([[0.4760],
        [0.2277],
        [0.1539]], grad_fn=<AddmmBackward0>)


## BackPropogation

In [ ]:
giris_veri = torch.tensor(
    [[0.4680, 0.1450, 0.1029, 0.3760, 0.5813, 0.4607, 0.8840, 0.9123, 0.6441,
         0.5628],
        [0.7681, 0.2212, 0.9511, 0.4000, 0.2130, 0.7685, 0.8511, 0.2762, 0.5940,
         0.8605],
    [0.4178, 0.9666, 0.2885, 0.1685, 0.2009, 0.7904, 0.1492, 0.2379, 0.9642,
        0.9226]]
)
etiket = torch.tensor([[1],[0],[1]])

In [ ]:
model = nn.Sequential(
    nn.Linear(10,8),
    nn.Linear(8,4),
    nn.Linear(4,1),
     nn.Sigmoid()
)
cikti = model(giris_veri)
print(cikti)

tensor([[0.3633],
        [0.3817],
        [0.3740]], grad_fn=<SigmoidBackward0>)


In [ ]:
criterion = nn.BCELoss()
loss = criterion(cikti.double(),etiket.double())
loss.backward()   #Back Propogation

In [ ]:
model[1].weight.grad,model[1].bias.grad

(tensor([[ 3.0093e-02, -1.2826e-02, -8.6438e-03, -2.2902e-02,  8.3784e-04,
           3.3270e-03, -4.5566e-03, -2.0120e-02],
         [-5.0458e-02,  2.1506e-02,  1.4493e-02,  3.8401e-02, -1.4048e-03,
          -5.5785e-03,  7.6401e-03,  3.3735e-02],
         [-2.9347e-03,  1.2508e-03,  8.4295e-04,  2.2335e-03, -8.1707e-05,
          -3.2446e-04,  4.4436e-04,  1.9621e-03],
         [ 5.0021e-02, -2.1320e-02, -1.4368e-02, -3.8069e-02,  1.3927e-03,
           5.5303e-03, -7.5740e-03, -3.3443e-02]]),
 tensor([-0.0475,  0.0796,  0.0046, -0.0789]))

In [ ]:
print(*model.parameters())

Parameter containing:
tensor([[-0.0141, -0.1176,  0.0380,  0.2802, -0.0897,  0.1306, -0.2574, -0.3135,
         -0.2082,  0.1095],
        [-0.2215,  0.0173, -0.2077, -0.1293, -0.1454,  0.1358,  0.0438, -0.2717,
          0.2434,  0.1821],
        [ 0.0125,  0.1580,  0.1066, -0.2598, -0.1186,  0.1584, -0.2016,  0.1436,
         -0.0142,  0.3121],
        [ 0.1707, -0.1649, -0.2034,  0.0563,  0.0618,  0.0656,  0.0512,  0.0337,
          0.2076,  0.1803],
        [ 0.1982,  0.1854, -0.1651,  0.0059,  0.1687,  0.2481,  0.2640, -0.0969,
         -0.2520, -0.1046],
        [ 0.0081, -0.1997, -0.3106,  0.0706,  0.0792,  0.2801,  0.2326, -0.2947,
          0.1210, -0.1753],
        [ 0.0872, -0.1506, -0.0800,  0.0599, -0.0063,  0.0134,  0.2151, -0.2909,
          0.1911, -0.1903],
        [ 0.1036, -0.0872,  0.2440,  0.1168,  0.2709,  0.2655,  0.1252,  0.2708,
         -0.2437,  0.1502]], requires_grad=True) Parameter containing:
tensor([-0.2057,  0.1511, -0.1224,  0.0876, -0.1820, -0.0507,  

In [ ]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(),lr=0.001,momentum=0.95)
optimizer.step()

In [ ]:
toplam = 0
for params in model.parameters():
  toplam += params.numel()
toplam

129

In [ ]:
for epoch in range(num_epochs):
  for data in dataloader:
    optimizer.zero_grad()
    feature,target = data
    pred = model(feature)
    loss = criterion(pred,target)
    loss.backward()
    optimizer.step()

## ReLU ve LeakyReLU


In [ ]:
relu = nn.ReLU()
leak_relu = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
print(relu(x))
print(leak_relu(x))

tensor(0.)
tensor(-0.1000)
