In [125]:
import torch
import pandas as pd
import numpy as np

In [126]:
df = pd.read_csv("water_potability.csv")

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2011 entries, 0 to 2010
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2011 non-null   float64
 1   Hardness         2011 non-null   float64
 2   Solids           2011 non-null   float64
 3   Chloramines      2011 non-null   float64
 4   Sulfate          2011 non-null   float64
 5   Conductivity     2011 non-null   float64
 6   Organic_carbon   2011 non-null   float64
 7   Trihalomethanes  2011 non-null   float64
 8   Turbidity        2011 non-null   float64
 9   Potability       2011 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 157.2 KB


In [128]:
df.head()


,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,0.587349,0.577747,0.386298,0.568199,0.647347,0.292985,0.654522,0.795029,0.630115,0
1,0.643654,0.441300,0.314381,0.439304,0.514545,0.356685,0.377248,0.202914,0.520358,0
2,0.388934,0.470876,0.506122,0.524364,0.561537,0.142913,0.249922,0.401487,0.219973,0
3,0.725820,0.715942,0.506141,0.521683,0.751819,0.148683,0.467200,0.658678,0.242428,0
4,0.610517,0.532588,0.237701,0.270288,0.495155,0.494792,0.409721,0.469762,0.585049,0


In [129]:
df.Potability.value_counts()

0    1200
1     811
Name: Potability, dtype: int64

In [130]:
X = df.loc[:,("ph","Chloramines","Sulfate","Organic_carbon")].values
X

array([[0.58734916, 0.5681994 , 0.64734744, 0.65452157],
       [0.64365393, 0.43930405, 0.51454537, 0.37724796],
       [0.38893354, 0.52436351, 0.56153738, 0.24992171],
       ...,
       [0.81782618, 0.67077443, 0.36908889, 0.56326524],
       [0.42418706, 0.54163315, 0.61557214, 0.39778031],
       [0.32242529, 0.49213569, 0.65604679, 0.47142165]])

In [131]:
X.dtype

dtype('float64')

In [132]:
features = torch.tensor(X).float()
features,features.dtype

(tensor([[0.5873, 0.5682, 0.6473, 0.6545],
         [0.6437, 0.4393, 0.5145, 0.3772],
         [0.3889, 0.5244, 0.5615, 0.2499],
         ...,
         [0.8178, 0.6708, 0.3691, 0.5633],
         [0.4242, 0.5416, 0.6156, 0.3978],
         [0.3224, 0.4921, 0.6560, 0.4714]]),
 torch.float32)

In [133]:
y = df.loc[:,"Potability"].values
y

array([0, 0, 0, ..., 1, 1, 1])

In [134]:
target = torch.tensor(y)
target,target.dtype

(tensor([0, 0, 0,  ..., 1, 1, 1]), torch.int64)

In [135]:
from torch.utils.data import TensorDataset

In [136]:
dataset = TensorDataset(features,target)
ornek = dataset[0]
ornek

(tensor([0.5873, 0.5682, 0.6473, 0.6545]), tensor(0))

In [137]:
ornek_X,ornek_y = ornek
ornek_X,ornek_y

(tensor([0.5873, 0.5682, 0.6473, 0.6545]), tensor(0))

In [138]:
from torch.utils.data import DataLoader
batch_size = 100
shuffle = True
dataloader = DataLoader(dataset,batch_size=batch_size,shuffle=shuffle)

In [139]:
X,y = next(iter(dataloader))
X,y

(tensor([[0.5033, 0.3771, 0.6486, 0.6416],
         [0.5341, 0.3836, 0.4787, 0.3966],
         [0.6440, 0.5320, 0.4146, 0.6484],
         [0.4814, 0.4462, 0.6792, 0.5936],
         [0.7320, 0.6409, 0.6833, 0.1766],
         [0.6055, 0.2468, 0.6570, 0.2752],
         [0.7518, 0.5349, 0.4863, 0.6358],
         [0.5844, 0.3708, 0.5075, 0.7199],
         [0.4443, 0.1714, 0.5012, 0.5198],
         [0.3224, 0.4921, 0.6560, 0.4714],
         [0.4344, 0.2969, 0.5635, 0.5972],
         [0.5539, 0.3771, 0.6095, 0.5139],
         [0.5166, 0.3304, 0.4869, 0.4107],
         [0.5604, 0.2858, 0.4642, 0.4833],
         [0.5103, 0.3302, 0.3733, 0.2398],
         [0.4329, 0.3824, 0.6747, 0.3248],
         [0.4589, 0.5133, 0.4235, 0.6943],
         [0.5054, 0.4249, 0.6361, 0.5082],
         [0.7503, 0.4772, 0.6005, 0.5758],
         [0.5763, 0.5625, 0.5839, 0.6130],
         [0.3945, 0.4151, 0.4693, 0.6722],
         [0.6091, 0.4794, 0.5650, 0.5063],
         [0.3373, 0.4846, 0.5512, 0.5439],
         [0

In [140]:
import torch.nn as nn

## Modelin Oluşturulması

In [141]:
model = nn.Sequential(
    nn.Linear(4,16),
    nn.Linear(16,8),
    nn.Linear(8,1),
    nn.Sigmoid()
)

In [142]:
import torch.optim as optim
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01,momentum=0.94)


In [143]:
num_epochs = 10
for epoch in range(num_epochs):
  for data in dataloader:
    optimizer.zero_grad()
    feature,target = data
    pred = model(feature)
    # print(pred)
    # print(target)
    loss = criterion(pred,target.unsqueeze(1).float())
    loss.backward()
    optimizer.step()

In [147]:
import torchmetric
metric = torchmetrics.Accuracy(task="binary")
num_epochs = 10
for epoch in range(num_epochs):
  for data in dataloader:
    optimizer.zero_grad()
    feature,target = data
    pred = model(feature)
    # print(pred)
    # print(target)
    loss = criterion(pred,target.unsqueeze(1).float())
    acc = metric(pred,target.unsqueeze(1).float())
    loss.backward()
    optimizer.step()
acc = metric.compute()

ModuleNotFoundError: No module named 'torchmetric'

# OOP in pytorch

In [169]:
from sklearn.model_selection import train_test_split
df = pd.read_csv("water_potability.csv")
df_train,df_test = train_test_split(df,test_size=0.2,random_state=42)
# df_train.to_csv("water_train.csv",index=False)
# df_test.to_csv("water_test.csv",index=False)
df_train.shape
df_test.shape

(403, 10)

In [199]:
from torch.utils.data import Dataset
class WaterDataset(Dataset):
  def __init__(self,csv_path):
    super().__init__()
    df = pd.read_csv(csv_path)
    self.data = df.to_numpy()

  def __len__(self):
    return self.data.shape[0]

  def __getitem__(self,idx):
    feature = self.data[idx,:-1]
    label =self.data[idx,-1]
    return feature,label

dataset_train = WaterDataset("water_train.csv")
dataset_test = WaterDataset("water_test.csv")

In [178]:
next(iter(dataset_train))

(tensor([[0.4772, 0.6911, 0.1652, 0.3722],
         [0.3061, 0.3032, 0.4817, 0.6260],
         [0.5511, 0.4246, 0.4508, 0.4235],
         [0.6202, 0.5247, 0.5505, 0.6740],
         [0.4944, 0.5954, 0.6065, 0.5089],
         [0.7370, 0.7185, 0.8913, 0.4820],
         [0.4525, 0.4356, 0.5072, 0.2389],
         [0.8178, 0.6708, 0.3691, 0.5633],
         [0.4749, 0.3358, 0.5801, 0.4578],
         [0.5202, 0.6587, 0.7247, 0.8513],
         [0.4811, 0.5320, 0.7305, 0.5942]]),
 1.0)

In [213]:
from torch.utils.data import DataLoader
dataloader_train = DataLoader(
    dataset_train,
    batch_size=5,
    shuffle=True
)

## sequential model tanimi

In [180]:
model = nn.Sequential(
    nn.Linear(9,16),
    nn.ReLU(),
    nn.Linear(16,8),
    nn.ReLU(),
    nn.Linear(8,1),
    nn.Sigmoid()
)

In [216]:
class Net(nn.Module):
  def __init__(self):
    super(Net,self).__init__()
    self.fc1 =nn.Linear(9,32)
    self.fc2 =nn.Linear(32,16)
    self.fc3 =nn.Linear(16,8)
    self.fc4 =nn.Linear(8,4)
    self.fc5 =nn.Linear(4,1)
    self.double()

  def forward(self,x):
    x = nn.functional.relu(self.fc1(x))
    x = nn.functional.relu(self.fc2(x))
    x = nn.functional.relu(self.fc3(x))
    x = nn.functional.relu(self.fc4(x))
    x = nn.functional.sigmoid(self.fc5(x))
    return x



## Eğitim Döngüsü

In [208]:
# %pip install torchmetrics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 841.5/841.5 kB 11.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 37.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 51.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 54.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 719.9 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 3.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━

In [ ]:
from torchmetrics import Accuracy

acc = Accuracy(task="binary")
acc.reset()
net = Net()
criterion = nn.BCELoss()
optimizer = optim.Adagrad(net.parameters(),lr=0.01)
for epoch in range(10):
  for features, labels in dataloader_train:
    optimizer.zero_grad()
    outputs = net(features)
    preds = (outputs>=0.5).float()
    acc(preds,labels.view(-1,1))
    loss = criterion(outputs,labels.view(-1,1))
    loss.backward()
    optimizer.step()

accuracy = acc.compute()
accuracy