In [ ]:
   import pandas as pd
import re
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from nltk import FreqDist
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from snowballstemmer import TurkishStemmer
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
cumle = """Açıklanan gerekçelerle BAŞVURUNUN KABULÜNE,
5510 sayılı Kanunun Geçici 94'üncü maddesini açıklamak, yorumlamak ve nasıl uygulanacağını
göstermek amacını taşıyacak olan Genelgenin olası hak mahrumiyetlerini bertaraf etme amacıyla
ivedi bir şekilde çıkarılması gerektiği hususunda
SOSYAL GÜVENLİK KURUMU BAŞKANLIĞINA TAVSİYEDE BULUNULMASINA
6328 sayılı Kamu Denetçiliği Kurumu Kanununun 20 nci maddesinin üçüncü fıkrası uyarınca,
Sosyal Güvenlik Kurumu Başkanlığı tarafından bu karar üzerine tesis edilecek işlemin otuz gün
içinde Kurumumuza bildirilmesinin zorunlu olduğuna,Kararın BAŞVURAN ve SOSYAL GÜVENLİK KURUMU BAŞKANLIĞINA tebliğine,
Türkiye Cumhuriyeti Kamu Başdenetçisince karar verildi.
25.12.2023 25.12.2023   20/05/2023"""

In [ ]:
def metin_temiz(metin):

  # noktalama işaretlerini temizle
  metin = re.sub(r'[^\w\s]','',metin)
  # fazla boşlukları kaldırma
  metin = re.sub(' +',' ',metin)
  print("metin_temiz => :",metin)
  # küçük harfe dönüştürme
  metin = metin.lower()
  return metin
metin_temiz(cumle)

metin_temiz => : Açıklanan gerekçelerle BAŞVURUNUN KABULÜNE
5510 sayılı Kanunun Geçici 94üncü maddesini açıklamak yorumlamak ve nasıl uygulanacağını
göstermek amacını taşıyacak olan Genelgenin olası hak mahrumiyetlerini bertaraf etme amacıyla
ivedi bir şekilde çıkarılması gerektiği hususunda
SOSYAL GÜVENLİK KURUMU BAŞKANLIĞINA TAVSİYEDE BULUNULMASINA
6328 sayılı Kamu Denetçiliği Kurumu Kanununun 20 nci maddesinin üçüncü fıkrası uyarınca
Sosyal Güvenlik Kurumu Başkanlığı tarafından bu karar üzerine tesis edilecek işlemin otuz gün
içinde Kurumumuza bildirilmesinin zorunlu olduğunaKararın BAŞVURAN ve SOSYAL GÜVENLİK KURUMU BAŞKANLIĞINA tebliğine
Türkiye Cumhuriyeti Kamu Başdenetçisince karar verildi
25122023 25122023 20052023


'açıklanan gerekçelerle başvurunun kabulüne\n5510 sayılı kanunun geçici 94üncü maddesini açıklamak yorumlamak ve nasıl uygulanacağını\ngöstermek amacını taşıyacak olan genelgenin olası hak mahrumiyetlerini bertaraf etme amacıyla\nivedi bir şekilde çıkarılması gerektiği hususunda\nsosyal güvenli̇k kurumu başkanliğina tavsi̇yede bulunulmasina\n6328 sayılı kamu denetçiliği kurumu kanununun 20 nci maddesinin üçüncü fıkrası uyarınca\nsosyal güvenlik kurumu başkanlığı tarafından bu karar üzerine tesis edilecek işlemin otuz gün\niçinde kurumumuza bildirilmesinin zorunlu olduğunakararın başvuran ve sosyal güvenli̇k kurumu başkanliğina tebliğine\ntürkiye cumhuriyeti kamu başdenetçisince karar verildi\n25122023 25122023 20052023'

In [ ]:
def cumle_cikar(metin):
  return metin.split(".")

In [ ]:
def kelime_parcala(metin):
  # cümlelere ayırma
  cumleler = sent_tokenize(metin)
  # kelimelere ayırma
  kelimeler = [word_tokenize(cumle) for cumle in cumleler]
  return kelimeler
kelime_parcala(metin_temiz(cumle))

In [ ]:
set(stopwords.words("turkish"))

In [ ]:
def durdurma_kelimeleri_kaldır(kelimeler):
  # Türkçe durdurma kelimelerini al
  dur_kelimeler = set(stopwords.words("turkish"))
  kelimeler = [kelime for kelime in kelimeler[0] if kelime not in dur_kelimeler]
  return kelimeler
durdurma_kelimeleri_kaldır(kelime_parcala(metin_temiz(cumle)))

In [ ]:
def kok_bul(kelimeler):
  # Türkçe Kök Bulucu
  kok_bulucu = TurkishStemmer()
  # kelimeleri köklerine indirgeme
  kokler = [kok_bulucu.stemWord(kelime) for kelime in kelimeler]
  return kokler
kok_bul(durdurma_kelimeleri_kaldır(kelime_parcala(metin_temiz(cumle))))

In [ ]:
def cumleleri_hazirla(cumleler):
    hazir_cumlelerList = []
    # print("cumleleri_hazirla 1=> :",cumleler)
    hazir_cumleler = metin_temiz(cumleler)
    # print("cumleleri_hazirla 2=> :",hazir_cumleler)
    hazir_cumleler = kelime_parcala(hazir_cumleler)
    # print("cumleleri_hazirla 3=> :",hazir_cumleler)
    hazir_cumleler = durdurma_kelimeleri_kaldır(hazir_cumleler)
    # print("cumleleri_hazirla 4=> :",hazir_cumleler)
    hazir_cumleler = kok_bul(hazir_cumleler)
    # print("cumleleri_hazirla 5=> :",hazir_cumleler)
    hazir_cumlelerList.append(hazir_cumleler)
    return hazir_cumlelerList
cumleleri_hazirla(cumle)


cumleleri_hazirla 1=> : Açıklanan gerekçelerle BAŞVURUNUN KABULÜNE,
5510 sayılı Kanunun Geçici 94'üncü maddesini açıklamak, yorumlamak ve nasıl uygulanacağını
göstermek amacını taşıyacak olan Genelgenin olası hak mahrumiyetlerini bertaraf etme amacıyla
ivedi bir şekilde çıkarılması gerektiği hususunda
SOSYAL GÜVENLİK KURUMU BAŞKANLIĞINA TAVSİYEDE BULUNULMASINA
6328 sayılı Kamu Denetçiliği Kurumu Kanununun 20 nci maddesinin üçüncü fıkrası uyarınca,
Sosyal Güvenlik Kurumu Başkanlığı tarafından bu karar üzerine tesis edilecek işlemin otuz gün
içinde Kurumumuza bildirilmesinin zorunlu olduğuna,Kararın BAŞVURAN ve SOSYAL GÜVENLİK KURUMU BAŞKANLIĞINA tebliğine,
Türkiye Cumhuriyeti Kamu Başdenetçisince karar verildi.
25.12.2023 25.12.2023   20/05/2023
metin_temiz => : Açıklanan gerekçelerle BAŞVURUNUN KABULÜNE
5510 sayılı Kanunun Geçici 94üncü maddesini açıklamak yorumlamak ve nasıl uygulanacağını
göstermek amacını taşıyacak olan Genelgenin olası hak mahrumiyetlerini bertaraf etme amacıyla
iv

[['açıklana',
  'gerekçe',
  'başvur',
  'kabul',
  '5510',
  'sayıl',
  'kanu',
  'geçiç',
  '94üncü',
  'madde',
  'açıklamak',
  'yorumlamak',
  'uygulanacak',
  'göstermek',
  'amaç',
  'taşıyacak',
  'ola',
  'genelge',
  'olas',
  'hak',
  'mahrumiyet',
  'bertaraf',
  'etme',
  'amaç',
  'ivedi',
  'bir',
  'şekil',
  'çıkarılmas',
  'gerektik',
  'husu',
  'sosyal',
  'güvenli̇k',
  'kur',
  'başkanlik',
  'tavsi̇ye',
  'bulunulmas',
  '6328',
  'sayıl',
  'kamu',
  'denetçilik',
  'kur',
  'kanun',
  '20',
  'nci',
  'madde',
  'üçüncü',
  'fıkras',
  'uyar',
  'sosyal',
  'güvenlik',
  'kur',
  'başkanlık',
  'taraf',
  'karar',
  'üzer',
  'tesis',
  'edilecek',
  'işle',
  'ot',
  'gün',
  'iç',
  'kurum',
  'bildirilme',
  'zorunlu',
  'olduğunakarar',
  'başvura',
  'sosyal',
  'güvenli̇k',
  'kur',
  'başkanlik',
  'teblik',
  'türki',
  'cumhuriyet',
  'kamu',
  'başdenetçi',
  'karar',
  'veril',
  '25122023',
  '25122023',
  '20052023']]

## Encoding

### One Hot Encoding

In [ ]:
import torch
sozluk = ["kedi","kopek","tavşan"]
sozluk_boyut = len(sozluk)
one_hot_vektor = torch.eye(sozluk_boyut)
one_hot_sozluk = {isim:one_hot_vektor[i] for i , isim in enumerate(sozluk)}
print(one_hot_sozluk)

{'kedi': tensor([1., 0., 0.]), 'kopek': tensor([0., 1., 0.]), 'tavşan': tensor([0., 0., 1.])}


### Bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
cumleler = ["Bu birinci döküman.","Bu döküman ikinci.","Bu üçüncü.","Bu birinci döküman mı?"]
X = vectorizer.fit_transform(cumleler)
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[1 1 1 0 0 0]
 [0 1 1 1 0 0]
 [0 1 0 0 0 1]
 [1 1 1 0 1 0]]
['birinci' 'bu' 'döküman' 'ikinci' 'mı' 'üçüncü']


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
cumleler = ["Bu birinci döküman.","Bu döküman ikinci.","Bu üçüncü.","Bu birinci döküman mı?"]
X = vectorizer.fit_transform(cumleler)
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0.69113141 0.4574528  0.55953044 0.         0.         0.        ]
 [0.         0.40264194 0.49248889 0.77157901 0.         0.        ]
 [0.         0.46263733 0.         0.         0.         0.88654763]
 [0.51971385 0.34399327 0.42075315 0.         0.65919112 0.        ]]
['birinci' 'bu' 'döküman' 'ikinci' 'mı' 'üçüncü']


##Veri Seti Sınıfı Oluşturma

In [ ]:
from torch.utils.data import Dataset,DataLoader

class MetinDataset(Dataset):
    def __init__(self,encoded_metin):
      self.data = encoded_metin

    def __len__(self):
      return len(self.data)

    def __getitem__(self,index):
      return self.data[index]



In [ ]:

def metin_encode(cumleler):
    vectorizer = CountVectorizer() # BoW
    # vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(cumleler)
    encoded_metin = X.toarray()
    return encoded_metin,vectorizer



## Embedding

In [ ]:
import torch
from torch import nn
ornek1 = "Yaşamak bir ağaç gibi tek ve hür, bir orman gibi kardeşçesine."
ornektemiz = cumleleri_hazirla(ornek1)
encoded_ornek1,o_vectorizer = metin_encode(ornektemiz[0])
veriseti = MetinDataset(encoded_ornek1)
o_veriyukleme = DataLoader(veriseti,batch_size=2,shuffle=True)
embedding = nn.Embedding(num_embeddings=3,embedding_dim=50)
adim = 1
for batch in o_veriyukleme:
    print(adim)
    cikti = embedding(batch)
    print(cikti.shape)


cumleleri_hazirla 1=> : Yaşamak bir ağaç gibi tek ve hür, bir orman gibi kardeşçesine.
metin_temiz => : Yaşamak bir ağaç gibi tek ve hür bir orman gibi kardeşçesine
cumleleri_hazirla 2=> : yaşamak bir ağaç gibi tek ve hür bir orman gibi kardeşçesine
cumleleri_hazirla 3=> : [['yaşamak', 'bir', 'ağaç', 'gibi', 'tek', 've', 'hür', 'bir', 'orman', 'gibi', 'kardeşçesine']]
cumleleri_hazirla 4=> : ['yaşamak', 'bir', 'ağaç', 'tek', 'hür', 'bir', 'orman', 'kardeşçesine']
cumleleri_hazirla 5=> : ['yaşamak', 'bir', 'ağaç', 'tek', 'hür', 'bir', 'orma', 'kardeşçe']
1
torch.Size([2, 7, 50])
1
torch.Size([2, 7, 50])
1
torch.Size([2, 7, 50])
1
torch.Size([2, 7, 50])


## OOP NN

In [ ]:
from torch import nn
import torch.optim as optim

class NNModel(nn.Module):
  def __init__(self):
    super(NNModel,self).__init__()
    self.fc1 = nn.Linear(9,16)
    self.bn1 = nn.BatchNorm1d(16)
    self.fc2 = nn.Linear(16,8)
    self.fc3 = nn.Linear(8,1)

  def forward(self,x):
      x = nn.functional.relu(self.fc1(x))
      x = self.bn1(x)
      x = nn.function.elu(x)
      x = nn.functional.relu(self.fc2(x))
      x = nn.functional.sigmoid(self.fc3(x))
      return x


## Training Loop

In [ ]:

net = NNModule()

criterion = nn.BCELoss()
optimizer = optim.SGD(net.parameters(),lr=0.01)

for epoch in range(10):
   for features,labels in dataloader_train:
      optimizer.zero_grad()
      outputs = net(features)
      loss = criterion(outputs,labels.view(-1,1))
      loss.backwards()
      optimizer.step()

## Evaluation

In [ ]:
from torchmetrics import Accuracy


acc = Accuracy(task="binary")

net.eval()
with torch.no_grad():
    for features,labels in dataloader_test:
        outputs = net(features)
        preds = (outputs >= 0.5).float()
        acc(preds,labels.view(-1,1))


accuracy = acc.compute()
print(accuracy)

In [ ]:
layer = nn.Linear(8,1)
print(layer.weight)

Parameter containing:
tensor([[ 0.1498,  0.2777,  0.3032, -0.0206,  0.2225,  0.2742,  0.1165, -0.2783]],
       requires_grad=True)


In [ ]:
import torch.nn.init as init

init.kaiming_uniform_(layer.weight)
print(layer.weight)

Parameter containing:
tensor([[ 0.1744,  0.4348,  0.3363,  0.5308,  0.7480,  0.6894,  0.6407, -0.1480]],
       requires_grad=True)
