Suppor Vector Regressor

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df =  pd.read_csv("housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY


In [ ]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
df["total_bedrooms"].fillna(df["total_bedrooms"].mean(),inplace=True)

In [ ]:
np.random.seed(2)
rowNum = np.random.randint(1,df.shape[0])
realTestVal = df.iloc[rowNum,:]
df.drop(rowNum,axis=0,inplace=True)
df.reset_index(drop=True,inplace=True)

In [ ]:
realTestVal

longitude                -124.13
latitude                   40.79
housing_median_age          29.0
total_rooms               2474.0
total_bedrooms             453.0
population                1130.0
households                 427.0
median_income             2.8833
median_house_value       83000.0
ocean_proximity       NEAR OCEAN
Name: 2576, dtype: object

In [ ]:
X=df.drop("median_house_value",axis=1)
y=df["median_house_value"]

In [ ]:
df.ocean_proximity.value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2657
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[-1])],remainder="passthrough")
X = ct.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_scaled = sc.transform(X_train)
X_test_scaled = sc.transform(X_test)

In [ ]:
# pd.DataFrame(X_train_scaled)

In [ ]:
pd.DataFrame(X_train_scaled).isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [ ]:
from sklearn.svm import SVR
model = SVR(kernel="linear")
model.fit(X_train_scaled,y_train)

SVR(kernel='linear')

In [ ]:
y_preds = model.predict(X_test_scaled)

In [ ]:
from math import sqrt
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2_score(y_test,y_preds),sqrt(mean_squared_error(y_test,y_preds)),mean_absolute_error(y_test,y_preds)

(0.09579188120798754, 110228.97100585047, 79814.55874021027)

In [ ]:
dfTest =  pd.read_csv("housing.csv")

model.predict(sc.transform(ct.transform([realTestVal.drop("median_house_value")])))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([175940.00330215])

In [ ]:
realTestVal["median_house_value"]

83000.0

Decision Tree Regressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(random_state=5)
model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=5)

In [ ]:
y_preds = model.predict(X_test)

In [ ]:
from math import sqrt
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2_score(y_test,y_preds),sqrt(mean_squared_error(y_test,y_preds)),mean_absolute_error(y_test,y_preds)

(0.6544229476645913, 68145.00066753392, 43306.48207364341)

In [ ]:
model.predict(ct.transform([realTestVal.drop("median_house_value")]))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([81700.])

In [ ]:
realTestVal["median_house_value"]

83000.0

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
y_preds = regressor.predict(X_test)

In [ ]:
regressor.predict(ct.transform([realTestVal.drop("median_house_value")]))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([87320.])

In [ ]:
realTestVal["median_house_value"]

83000.0

In [ ]:
from math import sqrt
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2_score(y_test,y_preds),sqrt(mean_squared_error(y_test,y_preds)),mean_absolute_error(y_test,y_preds)

(0.8008682020748619, 51728.735183804165, 33485.249176356585)